apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: challenge-app-scaler
  namespace: challenger-05
spec:
  scaleTargetRef:
    kind: Deployment
    name: challenge-app          
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: loki                   
    metadata:
      serverAddress: http://loki.observability-pro:3100
      query: |
        sum(rate({app="challenge-app"} |= "Rate limit exceeded" [30s])) by (app)
      threshold: "0.01"           